### PR TITLE
capacitor bug fix

### PR DESCRIPTION
**Pull request by sanderclaeys**
Currently there are two bugs in the parsing of capacitors
- The base should be adjusted as before
- The sign is wrong. The power reference in OpenDSS is expressed in generator sign convention, but the parser  assumes load convention. This can be seen by observing that a capacitor creates a voltage drop instead of a voltage rise.

A unit test will follow later, as part of the matrix line charging parameters.

### CODE REVIEW

**Comment by pseudocubic** [comment]
I would prefer there to be a unit test for this, perhaps by adding a simple capacitor to a 3 bus case?

A note also needs to be added to the change log

**Comment by sanderclaeys** [comment]
I will get around to it this week. I will skip the matrix line shunts for now; it is easy enough to extended the ACP/ACR formulations but the BF ones will require more work

**Comment by sanderclaeys** [comment]
I added a unit test for the capacitor pf. A few values had to be updated in other tests (4 in total I think)

**Comment by ccoffrin** [comment]
LGTM.  

@pseudocubic, regarding the broken docs build, most likely the manifest.toml needs to be removed form the docs dir.

**Pull request merged**
